version: '3'
services:
  api:
    # build:
    #   context: .
    #   dockerfile: UserManagementAPI/Dockerfile
    image: mattwolfrob/user-mngmnt-api:latest
    ports:
      - "5000:80"
    depends_on:
      - mongodb

  frontend:
    # build:
    #   context: ./UserManagement
    #   dockerfile: Dockerfile
    image: mattwolfrob/user-mngmnt-frontend:latest
    ports:
      - "4200:80"
    links:
      - api

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
